http:
 connection:
  host: "0.0.0.0"
  port: "8083"
  
webService:
 connection:
   wsdlLocation: "get-routes-ws.wsdl"
   service: "Bookings"
   port: "BookingsSOAP"
   address: "http://localhost:8089/"
 